### ISSUE TITLE
Code attribution

### ISSUE THREAD

**Issue by michalkleiner** [gorriecoe/silverstripe-link#1]
Hi,

this looks like a bit enhanced copy or a code with a lot of inspiration taken from https://github.com/sheadawson/silverstripe-linkable by @sheadawson.

Would you mind attributing some credit in your Readme if that's the case or can you explain the close similarity, e.g. around configuring the allowed types or use of A tag attribute names?

Thanks
Michal

**Comment by gorriecoe** [comment]
Yes it is similar, however its based off a large rewrite I have done back in 2016 https://github.com/sheadawson/silverstripe-linkable/pull/53/files.  Since then I have continued to modified the majority of the code believe I require no acknowledgement.  If @sheadawson believes that it still requires then I may add something along the lines "Inspired by early versions of Linkable".

**Comment by michalkleiner** [comment]
Thanks for the response @gorriecoe and thank you for the explanation. I didn't know about the merged PR you'd contributed to Linkable. Apologies.
Some form of a mention and explaining what your module does extra or differently would certainly help. As a new SS dev, if I come across these two modules, I wouldn't know why to choose one over the other etc. Hope it makes sense.

**Comment by gorriecoe** [comment]
I intend to make a few updates soon,  but one of the main things I done is separate code into smaller modules.  I recommend checking out https://github.com/gorriecoe/silverstripe-linkfield, https://github.com/gorriecoe/silverstripe-menu, https://github.com/gorriecoe/silverstripe-embed and https://github.com/gorriecoe/silverstripe-action
